import React, { useState, useEffect, useRef } from 'react';
import { 
  BarChart, Bar, LineChart, Line, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell 
} from 'recharts';
import { 
  Briefcase, AlertTriangle, TrendingUp, DollarSign, Calendar, 
  Users, Sparkles, Activity, Menu, X, Search, BrainCircuit, Receipt, LayoutDashboard, Terminal, CheckCircle2, ShieldAlert, CheckCircle, Clock, Sun, Moon
} from 'lucide-react';
import { calculateMeetingCost, detectLeakage, calculateProjectRisk } from './lib/algorithms';
import { EMPLOYEES } from './lib/mockData';
// Generator for infinite live event stream
const generateRandomEvent = (idCounter) => {
  const titles = [
    { title: "Project Phoenix Architecture Sync", project: "Phoenix", keyMatch: 40, orgMatch: 20, attMatch: 20, histMatch: 15, baseConf: 95 },
    { title: "Project Delta - Client Kickoff", project: "Client Project Delta", keyMatch: 40, orgMatch: 20, attMatch: 15, histMatch: 20, baseConf: 95 },
    { title: "Daily Standup", project: "Operations", keyMatch: 25, orgMatch: 15, attMatch: 20, histMatch: 20, baseConf: 80 },
    { title: "Candidate Interview - Senior Dev", project: "Recruitment", keyMatch: 40, orgMatch: 20, attMatch: 20, histMatch: 10, baseConf: 90 },
    { title: "Design System Review", project: "Internal R&D", keyMatch: 35, orgMatch: 20, attMatch: 15, histMatch: 15, baseConf: 85 },
    { title: "Emergency Bug Fix", project: "Phoenix", keyMatch: 30, orgMatch: 20, attMatch: 20, histMatch: 15, baseConf: 85 },
    { title: "All Hands Meeting", project: "Operations", keyMatch: 20, orgMatch: 20, attMatch: 20, histMatch: 20, baseConf: 80 },
  ];
  const template = titles[Math.floor(Math.random() * titles.length)];
  const duration = [0.5, 1.0, 1.5, 2.0][Math.floor(Math.random() * 4)];
  const allEmployees = Object.keys(EMPLOYEES);
  const attendeeCount = Math.floor(Math.random() * Math.min(8, allEmployees.length)) + 2;
  const shuffled = [...allEmployees].sort(() => 0.5 - Math.random());
  const attendeeList = shuffled.slice(0, attendeeCount);
  
  return {
    id: `evt_live_${idCounter}`,
    title: template.title,
    description: "Autogenerated stream event.",
    organizer: attendeeList[0],
    attendees: attendeeCount,
    attendeeList: attendeeList,
    duration: duration,
    recurring: Math.random() > 0.5,
    ...template
  };
};

export default function App() {
  const [theme, setTheme] = useState('dark');
  const [enrichedEvents, setEnrichedEvents] = useState([]);
  const [selectedMeeting, setSelectedMeeting] = useState(null);
  const [selectedEmployee, setSelectedEmployee] = useState(null);
  
  // Automation System State
  const [isSystemActive, setIsSystemActive] = useState(false);
  const systemActiveRef = useRef(false);
  const [liveLogs, setLiveLogs] = useState([]);
  const [logStats, setLogStats] = useState({ total: 0, warnings: 0, risks: 0 });
  const [timeSeriesData, setTimeSeriesData] = useState([]);

  const [agentStatus, setAgentStatus] = useState({
    calendar: 'WAITING', attribution: 'WAITING', cost: 'WAITING', leakage: 'WAITING', risk: 'WAITING', executive: 'WAITING'
  });
  
  const [governanceStats, setGovernanceStats] = useState({ autoApproved: 0, manualReview: 0, rejected: 0 });
  const [activeTab, setActiveTab] = useState('stream');
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  
  const logsEndRef = useRef(null);

  // Auto-scroll logs
  useEffect(() => {
    if (logsEndRef.current) logsEndRef.current.scrollIntoView({ behavior: 'smooth' });
  }, [liveLogs]);

  const addLog = (agent, message, type = 'INFO') => {
    const time = new Date().toLocaleTimeString('en-US', { hour12: false });
    
    setLogStats(prev => ({
      total: prev.total + 1,
      warnings: prev.warnings + (type === 'WARNING' ? 1 : 0),
      risks: prev.risks + (type === 'RISK' ? 1 : 0)
    }));

    setLiveLogs(prev => {
      const newLogs = [...prev, { id: Date.now() + Math.random(), time, agent, message, type }];
      return newLogs.slice(-50); // Keep only last 50
    });
  };

  const delay = ms => new Promise(res => setTimeout(res, ms));

  // Infinite generator loop
  const startLiveStream = async () => {
    if (systemActiveRef.current) return;
    setIsSystemActive(true);
    systemActiveRef.current = true;
    
    setEnrichedEvents([]);
    setLiveLogs([]);
    setTimeSeriesData([]);
    setLogStats({ total: 0, warnings: 0, risks: 0 });
    setGovernanceStats({ autoApproved: 0, manualReview: 0, rejected: 0 });
    setSelectedMeeting(null);
    setSelectedEmployee(null);
    setMobileMenuOpen(false);
    
    addLog('System', 'Initialized autonomous agent pipeline.', 'SUCCESS');
    let idCounter = 1;
    let cumulativeCost = 0;
    const startTime = Date.now();

    while (systemActiveRef.current) {
      const e = generateRandomEvent(idCounter++);
      const cycleStartTime = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute:'2-digit', second:'2-digit', hour12: false });
      
      // 1. Calendar Agent
      setAgentStatus(prev => ({ ...prev, calendar: 'PROCESSING' }));
      addLog('Calendar', `Event Extracted: "${e.title}"`, 'INFO');
      await delay(500);
      setAgentStatus(prev => ({ ...prev, calendar: 'COMPLETED' }));

      // 2. Attribution Agent
      setAgentStatus(prev => ({ ...prev, attribution: 'PROCESSING' }));
      addLog('Attribution', `Confidence ${e.baseConf}% -> Attributed to [${e.project}]`, 'SUCCESS');
      await delay(400);
      setAgentStatus(prev => ({ ...prev, attribution: 'COMPLETED' }));

      if (e.baseConf >= 85) setGovernanceStats(s => ({ ...s, autoApproved: s.autoApproved + 1 }));
      else setGovernanceStats(s => ({ ...s, manualReview: s.manualReview + 1 }));

      // 3. Cost Agent
      setAgentStatus(prev => ({ ...prev, cost: 'PROCESSING' }));
      const costData = calculateMeetingCost(e);
      cumulativeCost += costData.meetingCost;
      addLog('Cost', `Workforce Cost Allocated: $${costData.meetingCost.toFixed(0)}`, 'INFO');
      await delay(400);
      setAgentStatus(prev => ({ ...prev, cost: 'COMPLETED' }));

      // 4. Leakage Agent
      setAgentStatus(prev => ({ ...prev, leakage: 'PROCESSING' }));
      const leakage = detectLeakage(e, costData.meetingCost, costData.employeeCosts);
      if (leakage.leakages.length > 0) addLog('Leakage', `Waste Detected: $${leakage.estimatedWaste.toFixed(0)}`, 'WARNING');
      else addLog('Leakage', `Efficiency optimal.`, 'SUCCESS');
      await delay(400);
      setAgentStatus(prev => ({ ...prev, leakage: 'COMPLETED' }));

      const enriched = { ...e, costData, leakage, confidence: e.baseConf };
      setEnrichedEvents(prev => [enriched, ...prev].slice(0, 50));

      // 5. Risk Agent
      setAgentStatus(prev => ({ ...prev, risk: 'PROCESSING' }));
      if (leakage.leakageScore > 40) addLog('Risk', `Project Risk Escalated.`, 'RISK');
      else addLog('Risk', `Global Project Risk Updated.`, 'INFO');
      await delay(400);
      setAgentStatus(prev => ({ ...prev, risk: 'COMPLETED' }));

      // 6. Executive Agent
      setAgentStatus(prev => ({ ...prev, executive: 'PROCESSING' }));
      
      const elapsedMinutes = Math.max(0.1, (Date.now() - startTime) / 60000);
      const throughput = (idCounter / elapsedMinutes).toFixed(0);

      setTimeSeriesData(prev => {
        const newData = [...prev, {
          time: cycleStartTime,
          cost: cumulativeCost,
          waste: leakage.estimatedWaste,
          throughput: Number(throughput)
        }];
        return newData.slice(-20); // Keep chart window clean
      });

      addLog('Executive', `Organizational Intelligence Synchronized.`, 'SUCCESS');
      await delay(400);
      setAgentStatus(prev => ({ ...prev, executive: 'COMPLETED' }));

      if (!systemActiveRef.current) break;
      await delay(1500);
      setAgentStatus({
        calendar: 'WAITING', attribution: 'WAITING', cost: 'WAITING', leakage: 'WAITING', risk: 'WAITING', executive: 'WAITING'
      });
    }
  };

  const haltLiveStream = () => {
    systemActiveRef.current = false;
    setIsSystemActive(false);
    addLog('System', 'Autonomous Agent OS Halted.', 'WARNING');
    setAgentStatus({
      calendar: 'WAITING', attribution: 'WAITING', cost: 'WAITING', leakage: 'WAITING', risk: 'WAITING', executive: 'WAITING'
    });
  };

  const totalWorkforceCost = enrichedEvents.reduce((s, e) => s + e.costData.meetingCost, 0);
  
  const projectsMap = enrichedEvents.reduce((acc, e) => {
    if (!acc[e.project]) acc[e.project] = { name: e.project, cost: 0, meetingCount: 0, uniqueAttendees: 0, totalLeakageScore: 0 };
    acc[e.project].cost += e.costData.meetingCost;
    acc[e.project].meetingCount += 1;
    acc[e.project].totalLeakageScore += e.leakage.leakageScore;
    acc[e.project].uniqueAttendees += e.attendees;
    return acc;
  }, {});

  const projectsList = Object.values(projectsMap).map(p => {
    const risk = calculateProjectRisk(p);
    return { ...p, riskScore: risk.riskScore, riskLevel: risk.riskLevel };
  }).sort((a,b) => b.cost - a.cost);

  const employeeMap = {};
  enrichedEvents.forEach(e => {
    if (e.costData?.employeeCosts) {
      Object.entries(e.costData.employeeCosts).forEach(([email, cost]) => {
        const emp = EMPLOYEES[email];
        const name = emp?.name || email;
        if (!employeeMap[name]) {
          employeeMap[name] = { 
            name, email, role: emp?.role, rate: emp?.rate,
            cost: 0, hoursWorked: 0, projects: {}, meetings: [] 
          };
        }
        employeeMap[name].cost += cost;
        employeeMap[name].hoursWorked += e.duration;
        employeeMap[name].meetings.push(e);
        
        if (!employeeMap[name].projects[e.project]) employeeMap[name].projects[e.project] = 0;
        employeeMap[name].projects[e.project] += e.duration;
      });
    }
  });
  const allEmployeesList = Object.values(employeeMap).sort((a, b) => b.cost - a.cost);
  const topEmployeesList = allEmployeesList.slice(0, 5); // Top 5 employees

  const roleMap = {};
  allEmployeesList.forEach(emp => {
    const role = emp.role || 'Unspecified';
    if (!roleMap[role]) roleMap[role] = { name: role, cost: 0, hours: 0 };
    roleMap[role].cost += emp.cost;
    roleMap[role].hours += emp.hoursWorked;
  });
  const roleData = Object.values(roleMap).filter(r => r.cost > 0).map(r => ({ ...r, fte: (r.hours / 40).toFixed(2) }));
  const pieColors = ['#8b5cf6', '#3b82f6', '#10b981', '#f59e0b', '#ec4899'];

  const highestCostProject = projectsList[0];
  const highestRiskProject = [...projectsList].sort((a,b) => b.riskScore - a.riskScore)[0];

  const formatCurrency = (v) => new Intl.NumberFormat('en-US', {style:'currency', currency:'USD', maximumFractionDigits:0}).format(v);

  const getLogColor = (type) => {
    if (type === 'SUCCESS') return 'text-emerald-500 dark:text-emerald-400';
    if (type === 'WARNING') return 'text-amber-500 dark:text-amber-400';
    if (type === 'RISK') return 'text-rose-500 dark:text-rose-400';
    return 'text-blue-500 dark:text-blue-400';
  };

  const getStatusColor = (status) => {
    if (status === 'PROCESSING') return 'text-emerald-600 bg-emerald-100 border-emerald-200 dark:text-emerald-400 dark:bg-emerald-400/10 dark:border-emerald-400/20';
    if (status === 'COMPLETED') return 'text-blue-600 bg-blue-100 border-blue-200 dark:text-blue-400 dark:bg-blue-400/10 dark:border-blue-400/20';
    return 'text-slate-500 bg-slate-100 border-slate-200 dark:bg-slate-800/50 dark:border-slate-700/50';
  };

  return (
    <div className={`${theme} min-h-screen font-sans flex flex-col selection:bg-emerald-500/30`}>
      <div className="bg-slate-50 text-slate-900 dark:bg-[#0B0F19] dark:text-slate-200 min-h-screen flex flex-col transition-colors duration-300">
        
        <nav className="bg-white dark:bg-[#111827] border-b border-slate-200 dark:border-slate-800 px-4 md:px-6 py-4 flex flex-col md:flex-row md:items-center justify-between sticky top-0 z-50 transition-colors duration-300">
          <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-start">
            <div className="flex items-center gap-3">
              <div className="bg-emerald-100 dark:bg-emerald-500/20 p-2 rounded-lg border border-emerald-200 dark:border-emerald-500/30">
                <BrainCircuit className="text-emerald-600 dark:text-emerald-400 w-6 h-6" />
              </div>
              <div>
                <h1 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white tracking-tight">Workforce Intelligence OS</h1>
              </div>
            </div>
            <div className="md:hidden flex items-center gap-2">
              <button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="p-2 text-slate-500 dark:text-slate-400">
                {theme === 'dark' ? <Sun className="w-5 h-5"/> : <Moon className="w-5 h-5"/>}
              </button>
              <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="p-2">
                {mobileMenuOpen ? <X className="w-6 h-6 text-slate-500 dark:text-slate-400" /> : <Menu className="w-6 h-6 text-slate-500 dark:text-slate-400" />}
              </button>
            </div>
          </div>
          
          <div className="hidden md:flex items-center gap-4">
            <button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="p-2 text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white transition-colors">
              {theme === 'dark' ? <Sun className="w-5 h-5"/> : <Moon className="w-5 h-5"/>}
            </button>

            {!isSystemActive && (
              <button onClick={startLiveStream} className="bg-emerald-600 text-white px-6 py-2 rounded-lg text-sm font-bold shadow-[0_0_15px_rgba(16,185,129,0.3)] hover:bg-emerald-500 transition-colors flex items-center gap-2">
                <Activity className="w-4 h-4" /> Boot OS
              </button>
            )}
            {isSystemActive && (
              <div className="flex items-center gap-3">
                <div className="bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20 px-4 py-2 rounded-lg text-sm font-bold flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse shadow-[0_0_8px_rgba(16,185,129,1)]"></div>
                  SYSTEM ACTIVE
                </div>
                <button onClick={haltLiveStream} className="bg-white dark:bg-slate-800 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-500/30 px-4 py-2 rounded-lg text-sm font-bold shadow-sm dark:shadow-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors flex items-center gap-2">
                  <ShieldAlert className="w-4 h-4" /> Halt OS
                </button>
              </div>
            )}
          </div>
        </nav>

        {mobileMenuOpen && (
          <div className="md:hidden bg-white dark:bg-[#111827] border-b border-slate-200 dark:border-slate-800 px-4 py-4 w-full flex flex-col gap-3 transition-colors duration-300">
            {!isSystemActive ? (
              <button onClick={startLiveStream} className="w-full bg-emerald-600 text-white px-4 py-3 rounded-lg text-sm font-bold shadow-lg flex justify-center items-center gap-2">
                <Activity className="w-4 h-4" /> Boot OS
              </button>
            ) : (
              <button onClick={haltLiveStream} className="w-full bg-slate-100 dark:bg-slate-800 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-500/30 px-4 py-3 rounded-lg text-sm font-bold shadow-lg flex justify-center items-center gap-2">
                <ShieldAlert className="w-4 h-4" /> Halt OS
              </button>
            )}
          </div>
        )}

        <main className="flex-1 w-full max-w-[1600px] mx-auto px-4 md:px-6 py-6 overflow-x-hidden flex flex-col xl:flex-row gap-6">
          
          {/* LEFT COLUMN */}
          <div className="flex-1 space-y-6 flex flex-col">
            
            <div className="flex bg-slate-200 dark:bg-[#1E293B] p-1 rounded-lg w-full md:w-fit border border-transparent dark:border-slate-700 transition-colors duration-300">
              <button onClick={() => setActiveTab('stream')} className={`flex items-center justify-center gap-2 flex-1 md:flex-none px-4 py-3 md:py-2 rounded-md text-sm font-bold transition-all ${activeTab==='stream' ? 'bg-white dark:bg-[#0F172A] text-emerald-600 dark:text-emerald-400 shadow-md border-transparent dark:border-slate-800' : 'text-slate-500 dark:text-slate-400'}`}><Activity className="w-4 h-4"/> Stream</button>
              <button onClick={() => setActiveTab('dashboard')} className={`flex items-center justify-center gap-2 flex-1 md:flex-none px-4 py-3 md:py-2 rounded-md text-sm font-bold transition-all ${activeTab==='dashboard' ? 'bg-white dark:bg-[#0F172A] text-emerald-600 dark:text-emerald-400 shadow-md border-transparent dark:border-slate-800' : 'text-slate-500 dark:text-slate-400'}`}><LayoutDashboard className="w-4 h-4"/> Projects</button>
              <button onClick={() => setActiveTab('employees')} className={`flex items-center justify-center gap-2 flex-1 md:flex-none px-4 py-3 md:py-2 rounded-md text-sm font-bold transition-all ${activeTab==='employees' ? 'bg-white dark:bg-[#0F172A] text-emerald-600 dark:text-emerald-400 shadow-md border-transparent dark:border-slate-800' : 'text-slate-500 dark:text-slate-400'}`}><Users className="w-4 h-4"/> Workforce</button>
            </div>

            {!isSystemActive && enrichedEvents.length === 0 ? (
              <div className="flex flex-col items-center justify-center flex-1 min-h-[500px] bg-white dark:bg-[#111827] rounded-2xl border border-slate-200 dark:border-slate-800 transition-colors duration-300">
                <BrainCircuit className="w-16 h-16 text-slate-300 dark:text-slate-700 mb-6" />
                <h2 className="text-2xl font-bold text-slate-800 dark:text-white mb-2 text-center">System Offline</h2>
                <p className="text-slate-500 dark:text-slate-400 max-w-sm mb-8 text-center px-4">Boot the OS to initiate real-time analytics and autonomous agent executions.</p>
              </div>
            ) : (
              <>
                {activeTab === 'stream' && (
                  <div className="flex flex-col gap-6">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                      <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 p-4 rounded-xl flex flex-col gap-1 shadow-sm dark:shadow-none transition-colors duration-300">
                        <span className="text-xs uppercase tracking-wider text-slate-500 font-bold">Auto Approved</span>
                        <span className="text-2xl font-black text-emerald-600 dark:text-emerald-400">{governanceStats.autoApproved}</span>
                      </div>
                      <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 p-4 rounded-xl flex flex-col gap-1 shadow-sm dark:shadow-none transition-colors duration-300">
                        <span className="text-xs uppercase tracking-wider text-slate-500 font-bold">Human Reviewed</span>
                        <span className="text-2xl font-black text-amber-500 dark:text-amber-400">{governanceStats.manualReview}</span>
                      </div>
                      <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 p-4 rounded-xl flex flex-col gap-1 shadow-sm dark:shadow-none transition-colors duration-300">
                        <span className="text-xs uppercase tracking-wider text-slate-500 font-bold">Rejected</span>
                        <span className="text-2xl font-black text-rose-600 dark:text-rose-400">{governanceStats.rejected}</span>
                      </div>
                      <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 p-4 rounded-xl flex flex-col justify-center items-center gap-1 shadow-sm dark:shadow-none transition-colors duration-300">
                        <span className="text-xs uppercase tracking-wider text-slate-500 font-bold">Audit Logs</span>
                        <span className="text-xs font-bold bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 px-3 py-1 rounded-full border border-emerald-200 dark:border-emerald-500/20 flex items-center gap-1">
                          <CheckCircle className="w-3 h-3"/> Active
                        </span>
                      </div>
                    </div>

                    <div className="space-y-4">
                      {enrichedEvents.map((e) => (
                        <div key={e.id} className="bg-white dark:bg-[#111827] rounded-xl border border-slate-200 dark:border-slate-800 p-4 md:p-5 hover:border-slate-300 dark:hover:border-slate-700 transition-all animate-in fade-in slide-in-from-top-4 duration-300 shadow-sm dark:shadow-none">
                          <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-2">
                                <span className="bg-violet-50 dark:bg-violet-500/10 text-violet-600 dark:text-violet-400 border border-violet-200 dark:border-violet-500/20 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider">
                                  {e.project}
                                </span>
                                {e.leakage.leakages.length > 0 && (
                                  <span className="bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-200 dark:border-amber-500/20 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider flex items-center gap-1">
                                    <AlertTriangle className="w-3 h-3"/> Leakage Detected
                                  </span>
                                )}
                              </div>
                              <h3 className="text-base font-bold text-slate-900 dark:text-white mb-1">{e.title}</h3>
                              <div className="text-xs text-slate-500 dark:text-slate-400 flex items-center gap-3">
                                <span className="flex items-center gap-1"><Users className="w-3 h-3"/> {e.attendees} attendees</span>
                                <span className="flex items-center gap-1"><Calendar className="w-3 h-3"/> {e.duration}h duration</span>
                              </div>
                            </div>

                            <div className="flex flex-row md:flex-col justify-between items-center md:items-end md:w-32 shrink-0 border-t md:border-t-0 border-slate-100 dark:border-slate-800 pt-3 md:pt-0">
                              <div className="text-left md:text-right">
                                <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-0.5">Allocated Cost</div>
                                <div className="text-lg font-black text-slate-900 dark:text-white">{formatCurrency(e.costData.meetingCost)}</div>
                              </div>
                              <button 
                                onClick={() => setSelectedMeeting(e)}
                                className="bg-slate-50 hover:bg-slate-100 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 px-3 py-1.5 rounded-lg text-xs font-bold border border-slate-200 dark:border-slate-700 transition flex items-center gap-2 mt-0 md:mt-3 shadow-sm"
                              >
                                <BrainCircuit className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> Explain
                              </button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeTab === 'dashboard' && (
                  <div className="space-y-6">
                    
                    {/* Predictive Forecast Card */}
                    <div className="bg-gradient-to-br from-slate-100 to-white dark:from-[#1E293B] dark:to-[#0F172A] rounded-2xl p-6 border border-slate-200 dark:border-slate-700 shadow-md dark:shadow-xl relative overflow-hidden transition-colors duration-300">
                      <div className="absolute top-0 right-0 p-8 opacity-5 text-slate-900 dark:text-white">
                        <TrendingUp className="w-48 h-48" />
                      </div>
                      <div className="relative z-10">
                        <div className="flex items-center gap-2 mb-6">
                          <Sparkles className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                          <h2 className="text-lg font-bold text-slate-900 dark:text-white tracking-tight">AI Forecast & Strategy</h2>
                        </div>
                        
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                          <div className="space-y-1">
                            <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Current Velocity</p>
                            <p className="text-2xl font-black text-slate-900 dark:text-white">{formatCurrency(totalWorkforceCost)}</p>
                          </div>
                          <div className="space-y-1 border-l-0 md:border-l border-slate-200 dark:border-slate-700 md:pl-6">
                            <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Projected Weekly</p>
                            <p className="text-2xl font-black text-rose-600 dark:text-rose-400">{formatCurrency(totalWorkforceCost * 8)}</p>
                          </div>
                          <div className="space-y-1 border-l-0 md:border-l border-slate-200 dark:border-slate-700 md:pl-6">
                            <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Main Driver</p>
                            <p className="text-sm font-semibold text-amber-600 dark:text-amber-400 leading-snug">Structural over-attendance in Operations syncs</p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 pb-8">
                      
                      {/* Graph 1: Cost Velocity */}
                      <div className="bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                          <TrendingUp className="w-4 h-4"/> Workforce Cost Velocity
                        </h3>
                        <div className="h-[200px] w-full">
                          <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={timeSeriesData}>
                              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={theme === 'dark' ? '#1E293B' : '#e2e8f0'} />
                              <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} />
                              <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} tickFormatter={v => `$${v}`} width={60} />
                              <Tooltip contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} />
                              <Line type="monotone" dataKey="cost" stroke="#3b82f6" strokeWidth={3} dot={false} isAnimationActive={false} />
                            </LineChart>
                          </ResponsiveContainer>
                        </div>
                      </div>

                      {/* Graph 2: Agent Throughput */}
                      <div className="bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                          <Activity className="w-4 h-4"/> Agent Throughput (Events/Min)
                        </h3>
                        <div className="h-[200px] w-full">
                          <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={timeSeriesData}>
                              <defs>
                                <linearGradient id="colorThroughput" x1="0" y1="0" x2="0" y2="1">
                                  <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                                  <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                                </linearGradient>
                              </defs>
                              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={theme === 'dark' ? '#1E293B' : '#e2e8f0'} />
                              <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} />
                              <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} width={40} />
                              <Tooltip contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} />
                              <Area type="step" dataKey="throughput" stroke="#10b981" fillOpacity={1} fill="url(#colorThroughput)" isAnimationActive={false} />
                            </AreaChart>
                          </ResponsiveContainer>
                        </div>
                      </div>

                      {/* Graph 3: Leakage Trend */}
                      <div className="bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                          <ShieldAlert className="w-4 h-4"/> Detected Waste Trend
                        </h3>
                        <div className="h-[200px] w-full">
                          <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={timeSeriesData}>
                              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={theme === 'dark' ? '#1E293B' : '#e2e8f0'} />
                              <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} />
                              <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} width={60} tickFormatter={v => `$${v}`} />
                              <Tooltip contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} cursor={{fill: theme === 'dark' ? '#1E293B' : '#f1f5f9'}} />
                              <Bar dataKey="waste" fill="#ef4444" radius={[2, 2, 0, 0]} isAnimationActive={false} />
                            </BarChart>
                          </ResponsiveContainer>
                        </div>
                      </div>

                      {/* Graph 4: Project Risk Heatmap */}
                      <div className="bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-4 flex items-center gap-2">
                          <Briefcase className="w-4 h-4"/> Project Risk Heatmap
                        </h3>
                        <div className="flex-1 grid grid-cols-2 gap-3">
                          {projectsList.slice(0, 4).map(p => (
                            <div key={p.name} className={`p-4 rounded-lg border flex flex-col justify-center ${p.riskLevel === 'HIGH' ? 'bg-rose-50 dark:bg-rose-500/10 border-rose-200 dark:border-rose-500/30' : p.riskLevel === 'MEDIUM' ? 'bg-amber-50 dark:bg-amber-500/10 border-amber-200 dark:border-amber-500/30' : 'bg-emerald-50 dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/30'}`}>
                              <span className="text-sm font-bold text-slate-800 dark:text-white truncate mb-1" title={p.name}>{p.name}</span>
                              <span className={`text-xs font-bold uppercase tracking-wider ${p.riskLevel === 'HIGH' ? 'text-rose-600 dark:text-rose-400' : p.riskLevel === 'MEDIUM' ? 'text-amber-600 dark:text-amber-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
                                Risk: {p.riskScore}
                              </span>
                            </div>
                          ))}
                          {projectsList.length === 0 && (
                            <div className="col-span-2 text-center text-slate-500 dark:text-slate-600 font-bold mt-10 text-sm">Awaiting Map Data...</div>
                          )}
                        </div>
                      </div>

                      {/* Graph 5: Employee Leaderboard (Full Width) */}
                      <div className="col-span-1 lg:col-span-2 bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                          <Users className="w-4 h-4"/> Top Employees by Workforce Cost
                        </h3>
                        <div className="h-[250px] w-full">
                          {topEmployeesList.length > 0 ? (
                            <ResponsiveContainer width="100%" height="100%">
                              <BarChart data={topEmployeesList} layout="vertical" margin={{ top: 0, right: 30, left: 30, bottom: 0 }} onClick={(data) => {
                                if(data && data.activePayload && data.activePayload.length > 0) {
                                  setSelectedEmployee(data.activePayload[0].payload);
                                }
                              }}>
                                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke={theme === 'dark' ? '#1E293B' : '#e2e8f0'} />
                                <XAxis type="number" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} tickFormatter={v => `$${v}`} />
                                <YAxis type="category" dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 12, fill: theme === 'dark' ? '#cbd5e1' : '#334155'}} width={100} style={{cursor: 'pointer'}} />
                                <Tooltip cursor={{fill: theme === 'dark' ? '#1E293B' : '#f1f5f9'}} contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} formatter={v => formatCurrency(v)} />
                                <Bar dataKey="cost" fill="#8b5cf6" radius={[0, 4, 4, 0]} barSize={20} isAnimationActive={false} style={{cursor: 'pointer'}} />
                              </BarChart>
                            </ResponsiveContainer>
                          ) : (
                            <div className="flex h-full items-center justify-center text-center text-slate-500 dark:text-slate-600 font-bold text-sm">
                              Awaiting Employee Data...
                            </div>
                          )}
                        </div>
                      </div>

                    </div>
                  </div>
                )}

                {activeTab === 'employees' && (
                  <div className="space-y-6">
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                      {/* Graph: Hours Distribution by Project per Employee */}
                      <div className="lg:col-span-2 bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-6 flex items-center gap-2">
                          <Activity className="w-4 h-4"/> Cross-Project Hours Distribution (Utilization)
                        </h3>
                        <div className="h-[350px] w-full">
                          {allEmployeesList.length > 0 ? (
                            <ResponsiveContainer width="100%" height="100%">
                              <BarChart data={allEmployeesList.map(emp => ({ name: emp.name, ...emp.projects }))} margin={{ left: -20 }} onClick={(data) => {
                                  if(data && data.activePayload && data.activePayload.length > 0) {
                                    const clickedName = data.activePayload[0].payload.name;
                                    const empData = allEmployeesList.find(e => e.name === clickedName);
                                    if (empData) setSelectedEmployee(empData);
                                  }
                                }}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={theme === 'dark' ? '#1E293B' : '#e2e8f0'} />
                                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} style={{cursor: 'pointer'}} />
                                <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b'}} tickFormatter={v => `${v}h`} width={60} />
                                <Tooltip formatter={(value) => `${value} hrs`} cursor={{fill: theme === 'dark' ? '#1E293B' : '#f1f5f9'}} contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} />
                                {Array.from(new Set(allEmployeesList.flatMap(emp => Object.keys(emp.projects)))).map((proj, i) => (
                                  <Bar key={proj} dataKey={proj} stackId="a" fill={['#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899', '#14b8a6'][i % 6]} isAnimationActive={false} style={{cursor: 'pointer'}} />
                                ))}
                              </BarChart>
                            </ResponsiveContainer>
                          ) : (
                            <div className="flex h-full items-center justify-center text-center text-slate-500 dark:text-slate-600 font-bold text-sm">Awaiting Map Data...</div>
                          )}
                        </div>
                      </div>

                      {/* HR Pie Chart: Cost by Role */}
                      <div className="lg:col-span-1 bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm transition-colors duration-300 flex flex-col">
                        <h3 className="text-xs font-bold uppercase text-slate-500 mb-2 flex items-center gap-2">
                          <Users className="w-4 h-4"/> Expenditure by Role
                        </h3>
                        <div className="flex-1 flex flex-col justify-center relative min-h-[250px]">
                          {roleData.length > 0 ? (
                            <ResponsiveContainer width="100%" height="100%">
                              <PieChart>
                                <Pie data={roleData} dataKey="cost" nameKey="name" cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} isAnimationActive={false}>
                                  {roleData.map((entry, index) => (
                                    <Cell key={`cell-${index}`} fill={pieColors[index % pieColors.length]} />
                                  ))}
                                </Pie>
                                <Tooltip formatter={(value, name, props) => [`${formatCurrency(value)} (${props.payload.fte} FTE)`, name]} contentStyle={{backgroundColor: theme === 'dark' ? '#0F172A' : '#ffffff', border: theme === 'dark' ? '1px solid #1E293B' : '1px solid #e2e8f0', borderRadius: '8px', color: theme === 'dark' ? '#fff' : '#0f172a'}} />
                              </PieChart>
                            </ResponsiveContainer>
                          ) : (
                            <div className="flex h-full items-center justify-center text-center text-slate-500 dark:text-slate-600 font-bold text-sm">Awaiting Role Data...</div>
                          )}
                          {/* Custom Legend */}
                          {roleData.length > 0 && (
                            <div className="mt-4 flex flex-col gap-2">
                              {roleData.map((role, i) => (
                                <div key={role.name} className="flex items-center justify-between text-xs">
                                  <div className="flex items-center gap-2">
                                    <div className="w-2 h-2 rounded-full" style={{backgroundColor: pieColors[i % pieColors.length]}}></div>
                                    <span className="font-bold text-slate-700 dark:text-slate-300">{role.name}</span>
                                  </div>
                                  <div className="text-slate-500 dark:text-slate-400">{role.fte} FTE</div>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Employee Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                      {allEmployeesList.map(emp => (
                        <div key={emp.email} onClick={() => setSelectedEmployee(emp)} className="bg-white dark:bg-[#111827] p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm hover:border-violet-400 dark:hover:border-violet-500 transition-all cursor-pointer">
                          <div className="flex justify-between items-start mb-3">
                            <div>
                              <div className="font-bold text-slate-900 dark:text-white text-base">{emp.name}</div>
                              <div className="text-xs text-slate-500 dark:text-slate-400">{emp.role}</div>
                            </div>
                            <div className="text-right">
                              <div className="text-sm font-black text-violet-600 dark:text-violet-400">{formatCurrency(emp.cost)}</div>
                            </div>
                          </div>
                          
                          <div className="space-y-1 mt-4">
                            <div className="flex justify-between text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                              <span>Hours Logged</span>
                              <span>{emp.hoursWorked}h</span>
                            </div>
                            <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                              <div className="h-full bg-violet-500" style={{ width: `${Math.min(100, (emp.hoursWorked / 40) * 100)}%`}}></div>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </>
            )}
          </div>

          {/* RIGHT COLUMN: AI Agent Monitor */}
          <div className="w-full xl:w-[400px] shrink-0 flex flex-col gap-4">
            
            <div className="bg-white dark:bg-[#111827] rounded-xl border border-slate-200 dark:border-slate-800 shadow-md dark:shadow-xl overflow-hidden flex flex-col shrink-0 transition-colors duration-300">
              <div className="bg-slate-50 dark:bg-[#1E293B] px-4 py-3 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between transition-colors duration-300">
                <span className="text-slate-800 dark:text-white text-xs font-bold uppercase tracking-wider flex items-center gap-2"><Activity className="w-4 h-4 text-emerald-600 dark:text-emerald-400"/> Live Agent Pipeline</span>
              </div>
              <div className="p-4 space-y-3">
                {[
                  { id: 'calendar', name: 'Calendar Agent', icon: Calendar },
                  { id: 'attribution', name: 'Attribution Agent', icon: Search },
                  { id: 'cost', name: 'Cost Agent', icon: Receipt },
                  { id: 'leakage', name: 'Leakage Agent', icon: ShieldAlert },
                  { id: 'risk', name: 'Risk Agent', icon: TrendingUp },
                  { id: 'executive', name: 'Executive Agent', icon: BrainCircuit },
                ].map(agent => (
                  <div key={agent.id} className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800/50 pb-2 last:border-0 last:pb-0">
                    <div className="flex items-center gap-3">
                      <div className={`p-1.5 rounded-md ${agentStatus[agent.id] === 'PROCESSING' ? 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 dark:shadow-[0_0_10px_rgba(16,185,129,0.3)]' : agentStatus[agent.id] === 'COMPLETED' ? 'bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400' : 'bg-slate-100 dark:bg-slate-800 text-slate-500'}`}>
                        <agent.icon className="w-3.5 h-3.5" />
                      </div>
                      <span className="text-sm font-bold text-slate-700 dark:text-slate-300">{agent.name}</span>
                    </div>
                    <div className={`px-2 py-0.5 rounded text-[10px] font-bold tracking-widest ${getStatusColor(agentStatus[agent.id])}`}>
                      {agentStatus[agent.id]}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white dark:bg-[#111827] rounded-xl border border-slate-200 dark:border-slate-800 shadow-md dark:shadow-xl overflow-hidden flex flex-col h-[250px] md:h-[350px] shrink-0 sticky top-24 transition-colors duration-300">
              <div className="bg-slate-50 dark:bg-[#1E293B] px-4 py-2 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between shrink-0 transition-colors duration-300">
                <span className="text-slate-800 dark:text-white text-xs font-bold uppercase tracking-wider flex items-center gap-2"><Terminal className="w-4 h-4 text-blue-600 dark:text-blue-400" /> Processing Feed</span>
                <div className="flex items-center gap-3 text-[10px] font-bold">
                  <span className="text-slate-500 dark:text-slate-400">EVT: <span className="text-slate-900 dark:text-white">{logStats.total}</span></span>
                  <span className="text-amber-500 dark:text-amber-400">WRN: <span className="text-slate-900 dark:text-white">{logStats.warnings}</span></span>
                  <span className="text-rose-500 dark:text-rose-400">RSK: <span className="text-slate-900 dark:text-white">{logStats.risks}</span></span>
                </div>
              </div>
              <div className="p-4 overflow-y-auto flex-1 font-mono text-[11px] leading-relaxed space-y-2.5 bg-slate-900 dark:bg-[#0B0F19]">
                {liveLogs.map((log) => (
                  <div key={log.id} className="animate-in fade-in slide-in-from-bottom-2 duration-300">
                    <span className="text-slate-500">[{log.time}]</span>{' '}
                    <span className={`font-bold ${getLogColor(log.type)}`}>
                      [{log.agent}]
                    </span>{' '}
                    <span className="text-slate-300">{log.message}</span>
                  </div>
                ))}
                <div ref={logsEndRef} />
                {liveLogs.length === 0 && !isSystemActive && (
                  <div className="text-center text-slate-500 mt-10 italic">Awaiting events...</div>
                )}
              </div>
            </div>

          </div>

          {/* EXPLAINABILITY DRAWER */}
          {selectedMeeting && (
            <div className="fixed inset-0 z-[100] flex justify-end bg-slate-900/50 dark:bg-[#0B0F19]/80 backdrop-blur-sm animate-in fade-in duration-200 p-0 md:p-4">
              <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 w-full max-w-sm md:rounded-2xl h-full md:h-auto overflow-y-auto shadow-2xl animate-in slide-in-from-right md:slide-in-from-bottom-4 duration-300 flex flex-col transition-colors duration-300">
                
                <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between sticky top-0 bg-white dark:bg-[#111827] z-10 transition-colors duration-300">
                  <h2 className="font-bold text-slate-900 dark:text-white text-lg flex items-center gap-2"><BrainCircuit className="text-emerald-600 dark:text-emerald-400 w-5 h-5"/> Explainability Trace</h2>
                  <button onClick={() => setSelectedMeeting(null)} className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition">
                    <X className="w-5 h-5 text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white" />
                  </button>
                </div>

                <div className="p-6">
                  <div className="mb-6">
                    <h3 className="text-xs uppercase tracking-widest text-slate-500 font-bold mb-2">Target Event</h3>
                    <div className="text-slate-900 dark:text-white font-bold text-lg mb-1">{selectedMeeting.title}</div>
                    <div className="text-slate-500 dark:text-slate-400 text-sm flex items-center gap-2"><Users className="w-4 h-4"/> {selectedMeeting.organizer}</div>
                  </div>

                  <div className="mb-6">
                    <h3 className="text-xs uppercase tracking-widest text-slate-500 font-bold mb-4">Why {selectedMeeting.project}?</h3>
                    <div className="space-y-5">
                      <div>
                        <div className="flex justify-between text-xs mb-1.5 font-semibold text-slate-700 dark:text-slate-300">
                          <span>Keyword Match Score</span>
                          <span className="text-emerald-600 dark:text-emerald-400">{selectedMeeting.keyMatch} / 40</span>
                        </div>
                        <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                          <div className="h-full bg-emerald-500" style={{ width: `${(selectedMeeting.keyMatch/40)*100}%`}}></div>
                        </div>
                      </div>
                      <div>
                        <div className="flex justify-between text-xs mb-1.5 font-semibold text-slate-700 dark:text-slate-300">
                          <span>Organizer Department</span>
                          <span className="text-blue-600 dark:text-blue-400">{selectedMeeting.orgMatch} / 20</span>
                        </div>
                        <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                          <div className="h-full bg-blue-500" style={{ width: `${(selectedMeeting.orgMatch/20)*100}%`}}></div>
                        </div>
                      </div>
                      <div>
                        <div className="flex justify-between text-xs mb-1.5 font-semibold text-slate-700 dark:text-slate-300">
                          <span>Attendee Vector Match</span>
                          <span className="text-violet-600 dark:text-violet-400">{selectedMeeting.attMatch} / 20</span>
                        </div>
                        <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                          <div className="h-full bg-violet-500" style={{ width: `${(selectedMeeting.attMatch/20)*100}%`}}></div>
                        </div>
                      </div>
                      <div>
                        <div className="flex justify-between text-xs mb-1.5 font-semibold text-slate-700 dark:text-slate-300">
                          <span>Historical Affinity</span>
                          <span className="text-amber-600 dark:text-amber-400">{selectedMeeting.histMatch} / 20</span>
                        </div>
                        <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                          <div className="h-full bg-amber-500" style={{ width: `${(selectedMeeting.histMatch/20)*100}%`}}></div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="bg-slate-50 dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 p-4 rounded-xl flex items-center justify-between shadow-inner transition-colors duration-300">
                    <span className="text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-widest">Final Confidence</span>
                    <span className="text-3xl font-black text-slate-900 dark:text-white">{selectedMeeting.confidence}%</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* EMPLOYEE PROFILE DRAWER */}
          {selectedEmployee && (
            <div className="fixed inset-0 z-[100] flex justify-end bg-slate-900/50 dark:bg-[#0B0F19]/80 backdrop-blur-sm animate-in fade-in duration-200 p-0 md:p-4">
              <div className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 w-full max-w-sm md:rounded-2xl h-full md:h-auto overflow-y-auto shadow-2xl animate-in slide-in-from-right md:slide-in-from-bottom-4 duration-300 flex flex-col transition-colors duration-300">
                
                <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between sticky top-0 bg-white dark:bg-[#111827] z-10 transition-colors duration-300">
                  <h2 className="font-bold text-slate-900 dark:text-white text-lg flex items-center gap-2"><Users className="text-violet-600 dark:text-violet-400 w-5 h-5"/> Employee Profile</h2>
                  <button onClick={() => setSelectedEmployee(null)} className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition">
                    <X className="w-5 h-5 text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white" />
                  </button>
                </div>

                <div className="p-6">
                  <div className="mb-6 flex flex-col gap-1">
                    <h3 className="text-2xl font-black text-slate-900 dark:text-white">{selectedEmployee.name}</h3>
                    <span className="text-sm font-bold text-slate-500 dark:text-slate-400 flex items-center gap-2">{selectedEmployee.role} • {formatCurrency(selectedEmployee.rate)}/hr</span>
                  </div>

                  <div className="mb-6 bg-slate-50 dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 p-4 rounded-xl shadow-inner transition-colors duration-300 grid grid-cols-2 gap-4">
                    <div>
                      <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-0.5">Hours in Meetings</div>
                      <div className="text-xl font-black text-slate-900 dark:text-white">{selectedEmployee.hoursWorked}h</div>
                    </div>
                    <div>
                      <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-0.5">Meeting Cost</div>
                      <div className="text-xl font-black text-violet-600 dark:text-violet-400">{formatCurrency(selectedEmployee.cost)}</div>
                    </div>
                    <div className="col-span-2">
                      <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Weekly Salary Capacity (40h)</div>
                      <div className="flex justify-between text-sm mb-1 font-semibold text-slate-700 dark:text-slate-300">
                        <span>{formatCurrency(selectedEmployee.cost)} spent</span>
                        <span className="text-slate-400">{formatCurrency(selectedEmployee.rate * 40)} total</span>
                      </div>
                      <div className="h-1.5 w-full bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div className="h-full bg-violet-500" style={{ width: `${Math.min(100, (selectedEmployee.cost / (selectedEmployee.rate * 40)) * 100)}%`}}></div>
                      </div>
                    </div>
                  </div>

                  <div className="mb-6">
                    <h3 className="text-xs uppercase tracking-widest text-slate-500 font-bold mb-3">Project Contributions</h3>
                    <div className="space-y-3">
                      {Object.entries(selectedEmployee.projects).sort((a,b) => b[1] - a[1]).map(([proj, hours]) => (
                        <div key={proj}>
                          <div className="flex justify-between text-xs mb-1 font-semibold text-slate-700 dark:text-slate-300">
                            <span className="truncate pr-2">{proj}</span>
                            <span className="text-emerald-600 dark:text-emerald-400 shrink-0">{hours}h</span>
                          </div>
                          <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                            <div className="h-full bg-emerald-500" style={{ width: `${(hours / selectedEmployee.hoursWorked)*100}%`}}></div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h3 className="text-xs uppercase tracking-widest text-slate-500 font-bold mb-3">Recent Calendar Activity</h3>
                    <div className="space-y-2 max-h-48 overflow-y-auto pr-2">
                      {selectedEmployee.meetings.map(m => (
                        <div key={m.id} className="bg-slate-50 dark:bg-slate-800/50 p-3 rounded-lg border border-slate-200 dark:border-slate-700/50">
                          <div className="text-xs font-bold text-slate-900 dark:text-white truncate mb-1">{m.title}</div>
                          <div className="flex justify-between items-center text-[10px] font-bold">
                            <span className="text-violet-600 dark:text-violet-400">{m.project}</span>
                            <span className="text-slate-500 dark:text-slate-400 flex items-center gap-1"><Clock className="w-3 h-3"/> {m.duration}h</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              </div>
            </div>
          )}

        </main>
      </div>
    </div>
  );
}
